# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'octron.ui'
##
## Created by: Qt User Interface Compiler version 5.15.16
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *  # type: ignore
from PySide2.QtGui import *  # type: ignore
from PySide2.QtWidgets import *  # type: ignore


class Ui_octron_widgetui(object):
    def setupUi(self, octron_widgetui):
        if not octron_widgetui.objectName():
            octron_widgetui.setObjectName(u"octron_widgetui")
        octron_widgetui.setEnabled(True)
        octron_widgetui.resize(410, 700)
        octron_widgetui.setMinimumSize(QSize(410, 700))
        octron_widgetui.setMaximumSize(QSize(410, 700))
        octron_widgetui.setCursor(QCursor(Qt.ArrowCursor))
        octron_widgetui.setWindowOpacity(1.000000000000000)
        self.verticalLayoutWidget = QWidget(octron_widgetui)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(0, 0, 412, 691))
        self.mainLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.mainLayout.setSpacing(10)
        self.mainLayout.setObjectName(u"mainLayout")
        self.mainLayout.setSizeConstraint(QLayout.SizeConstraint.SetNoConstraint)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.octron_logo = QLabel(self.verticalLayoutWidget)
        self.octron_logo.setObjectName(u"octron_logo")
        self.octron_logo.setEnabled(True)
        self.octron_logo.setMinimumSize(QSize(410, 120))
        self.octron_logo.setMaximumSize(QSize(410, 120))
        self.octron_logo.setBaseSize(QSize(0, 0))
        self.octron_logo.setLineWidth(0)
        self.octron_logo.setPixmap(QPixmap(u"octron_logo.svg"))
        self.octron_logo.setAlignment(Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignTop)

        self.mainLayout.addWidget(self.octron_logo, 0, Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignTop)

        self.toolBox = QToolBox(self.verticalLayoutWidget)
        self.toolBox.setObjectName(u"toolBox")
        self.toolBox.setEnabled(True)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMinimumSize(QSize(410, 550))
        self.toolBox.setMaximumSize(QSize(410, 550))
        self.toolBox.setCursor(QCursor(Qt.ArrowCursor))
        self.toolBox.setFrameShape(QFrame.Shape.NoFrame)
        self.toolBox.setFrameShadow(QFrame.Shadow.Plain)
        self.toolBox.setLineWidth(0)
        self.toolBox.setMidLineWidth(0)
        self.project_tab = QWidget()
        self.project_tab.setObjectName(u"project_tab")
        self.project_tab.setGeometry(QRect(0, 0, 410, 414))
        sizePolicy1 = QSizePolicy(QSizePolicy.Ignored, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.project_tab.sizePolicy().hasHeightForWidth())
        self.project_tab.setSizePolicy(sizePolicy1)
        self.verticalLayoutWidget_3 = QWidget(self.project_tab)
        self.verticalLayoutWidget_3.setObjectName(u"verticalLayoutWidget_3")
        self.verticalLayoutWidget_3.setGeometry(QRect(0, -1, 402, 402))
        self.project_vertical_layout = QVBoxLayout(self.verticalLayoutWidget_3)
        self.project_vertical_layout.setSpacing(30)
        self.project_vertical_layout.setObjectName(u"project_vertical_layout")
        self.project_vertical_layout.setContentsMargins(0, 0, 0, 15)
        self.folder_sect_groupbox = QGroupBox(self.verticalLayoutWidget_3)
        self.folder_sect_groupbox.setObjectName(u"folder_sect_groupbox")
        sizePolicy2 = QSizePolicy(QSizePolicy.Maximum, QSizePolicy.Maximum)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.folder_sect_groupbox.sizePolicy().hasHeightForWidth())
        self.folder_sect_groupbox.setSizePolicy(sizePolicy2)
        self.folder_sect_groupbox.setMinimumSize(QSize(400, 70))
        self.folder_sect_groupbox.setMaximumSize(QSize(400, 70))
        self.horizontalLayout_11 = QHBoxLayout(self.folder_sect_groupbox)
        self.horizontalLayout_11.setSpacing(20)
        self.horizontalLayout_11.setObjectName(u"horizontalLayout_11")
        self.horizontalLayout_11.setContentsMargins(9, 9, 9, 9)
        self.create_project_btn = QPushButton(self.folder_sect_groupbox)
        self.create_project_btn.setObjectName(u"create_project_btn")
        self.create_project_btn.setMinimumSize(QSize(100, 25))
        self.create_project_btn.setMaximumSize(QSize(100, 25))

        self.horizontalLayout_11.addWidget(self.create_project_btn, 0, Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.project_folder_path_label = QLabel(self.folder_sect_groupbox)
        self.project_folder_path_label.setObjectName(u"project_folder_path_label")
        self.project_folder_path_label.setEnabled(False)
        self.project_folder_path_label.setMinimumSize(QSize(250, 35))
        self.project_folder_path_label.setMaximumSize(QSize(250, 35))
        self.project_folder_path_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.project_folder_path_label.setWordWrap(True)
        self.project_folder_path_label.setMargin(0)

        self.horizontalLayout_11.addWidget(self.project_folder_path_label, 0, Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignVCenter)


        self.project_vertical_layout.addWidget(self.folder_sect_groupbox, 0, Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignTop)

        self.project_video_drop_groupbox = QGroupBox(self.verticalLayoutWidget_3)
        self.project_video_drop_groupbox.setObjectName(u"project_video_drop_groupbox")
        sizePolicy2.setHeightForWidth(self.project_video_drop_groupbox.sizePolicy().hasHeightForWidth())
        self.project_video_drop_groupbox.setSizePolicy(sizePolicy2)
        self.project_video_drop_groupbox.setMinimumSize(QSize(400, 150))
        self.project_video_drop_groupbox.setMaximumSize(QSize(400, 150))
        self.horizontalLayout = QHBoxLayout(self.project_video_drop_groupbox)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(9, 9, 9, 9)
        self.video_file_drop_widget = QWidget(self.project_video_drop_groupbox)
        self.video_file_drop_widget.setObjectName(u"video_file_drop_widget")
        self.video_file_drop_widget.setMinimumSize(QSize(380, 110))
        self.video_file_drop_widget.setMaximumSize(QSize(380, 110))

        self.horizontalLayout.addWidget(self.video_file_drop_widget)


        self.project_vertical_layout.addWidget(self.project_video_drop_groupbox, 0, Qt.AlignmentFlag.AlignTop)

        self.project_existing_data_groupbox = QGroupBox(self.verticalLayoutWidget_3)
        self.project_existing_data_groupbox.setObjectName(u"project_existing_data_groupbox")
        self.project_existing_data_groupbox.setEnabled(False)
        sizePolicy2.setHeightForWidth(self.project_existing_data_groupbox.sizePolicy().hasHeightForWidth())
        self.project_existing_data_groupbox.setSizePolicy(sizePolicy2)
        self.project_existing_data_groupbox.setMinimumSize(QSize(400, 140))
        self.project_existing_data_groupbox.setMaximumSize(QSize(400, 140))
        self.horizontalLayout_9 = QHBoxLayout(self.project_existing_data_groupbox)
        self.horizontalLayout_9.setSpacing(20)
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.horizontalLayout_9.setContentsMargins(9, 9, 9, 9)
        self.existing_data_table = QTableView(self.project_existing_data_groupbox)
        self.existing_data_table.setObjectName(u"existing_data_table")
        self.existing_data_table.setMinimumSize(QSize(380, 100))
        self.existing_data_table.setMaximumSize(QSize(380, 100))
        self.existing_data_table.setEditTriggers(QAbstractItemView.EditTrigger.AnyKeyPressed|QAbstractItemView.EditTrigger.EditKeyPressed|QAbstractItemView.EditTrigger.SelectedClicked)
        self.existing_data_table.setProperty("showDropIndicator", False)
        self.existing_data_table.setDragDropOverwriteMode(False)
        self.existing_data_table.setSelectionMode(QAbstractItemView.SelectionMode.SingleSelection)
        self.existing_data_table.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.existing_data_table.setGridStyle(Qt.PenStyle.SolidLine)
        self.existing_data_table.setSortingEnabled(False)
        self.existing_data_table.setWordWrap(False)
        self.existing_data_table.setCornerButtonEnabled(False)
        self.existing_data_table.horizontalHeader().setCascadingSectionResizes(True)
        self.existing_data_table.horizontalHeader().setMinimumSectionSize(85)
        self.existing_data_table.horizontalHeader().setDefaultSectionSize(85)
        self.existing_data_table.horizontalHeader().setHighlightSections(False)
        self.existing_data_table.verticalHeader().setVisible(False)
        self.existing_data_table.verticalHeader().setMinimumSectionSize(20)
        self.existing_data_table.verticalHeader().setDefaultSectionSize(20)
        self.existing_data_table.verticalHeader().setHighlightSections(False)

        self.horizontalLayout_9.addWidget(self.existing_data_table, 0, Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignVCenter)


        self.project_vertical_layout.addWidget(self.project_existing_data_groupbox, 0, Qt.AlignmentFlag.AlignTop)

        icon = QIcon()
        icon.addFile(u"icons/noun-project-7158867.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.toolBox.addItem(self.project_tab, icon, u"Manage project")
        self.annotate_tab = QWidget()
        self.annotate_tab.setObjectName(u"annotate_tab")
        self.annotate_tab.setGeometry(QRect(0, 0, 405, 414))
        sizePolicy1.setHeightForWidth(self.annotate_tab.sizePolicy().hasHeightForWidth())
        self.annotate_tab.setSizePolicy(sizePolicy1)
        self.annotate_tab.setMaximumSize(QSize(405, 700))
        self.verticalLayoutWidget_2 = QWidget(self.annotate_tab)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(0, 0, 402, 341))
        self.annotate_vertical_layout = QVBoxLayout(self.verticalLayoutWidget_2)
        self.annotate_vertical_layout.setSpacing(20)
        self.annotate_vertical_layout.setObjectName(u"annotate_vertical_layout")
        self.annotate_vertical_layout.setContentsMargins(0, 0, 0, 15)
        self.horizontalGroupBox = QGroupBox(self.verticalLayoutWidget_2)
        self.horizontalGroupBox.setObjectName(u"horizontalGroupBox")
        sizePolicy3 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.horizontalGroupBox.sizePolicy().hasHeightForWidth())
        self.horizontalGroupBox.setSizePolicy(sizePolicy3)
        self.horizontalGroupBox.setMinimumSize(QSize(400, 60))
        self.horizontalGroupBox.setMaximumSize(QSize(400, 60))
        self.horizontalLayout_8 = QHBoxLayout(self.horizontalGroupBox)
        self.horizontalLayout_8.setSpacing(20)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.horizontalLayout_8.setContentsMargins(9, 9, 9, 9)
        self.sam2model_list = QComboBox(self.horizontalGroupBox)
        self.sam2model_list.addItem("")
        self.sam2model_list.setObjectName(u"sam2model_list")
        self.sam2model_list.setMinimumSize(QSize(167, 25))
        self.sam2model_list.setMaximumSize(QSize(167, 25))

        self.horizontalLayout_8.addWidget(self.sam2model_list, 0, Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.load_sam2model_btn = QPushButton(self.horizontalGroupBox)
        self.load_sam2model_btn.setObjectName(u"load_sam2model_btn")
        self.load_sam2model_btn.setMinimumSize(QSize(0, 25))
        self.load_sam2model_btn.setMaximumSize(QSize(250, 25))

        self.horizontalLayout_8.addWidget(self.load_sam2model_btn, 0, Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignVCenter)


        self.annotate_vertical_layout.addWidget(self.horizontalGroupBox, 0, Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignTop)

        self.annotate_layer_create_groupbox = QGroupBox(self.verticalLayoutWidget_2)
        self.annotate_layer_create_groupbox.setObjectName(u"annotate_layer_create_groupbox")
        sizePolicy3.setHeightForWidth(self.annotate_layer_create_groupbox.sizePolicy().hasHeightForWidth())
        self.annotate_layer_create_groupbox.setSizePolicy(sizePolicy3)
        self.annotate_layer_create_groupbox.setMinimumSize(QSize(400, 90))
        self.annotate_layer_create_groupbox.setMaximumSize(QSize(400, 90))
        self.gridLayout = QGridLayout(self.annotate_layer_create_groupbox)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout.setHorizontalSpacing(20)
        self.gridLayout.setVerticalSpacing(9)
        self.gridLayout.setContentsMargins(9, 9, 9, 9)
        self.create_projection_layer_btn = QPushButton(self.annotate_layer_create_groupbox)
        self.create_projection_layer_btn.setObjectName(u"create_projection_layer_btn")
        self.create_projection_layer_btn.setMinimumSize(QSize(110, 25))
        self.create_projection_layer_btn.setMaximumSize(QSize(110, 25))

        self.gridLayout.addWidget(self.create_projection_layer_btn, 1, 0, 1, 1, Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.layer_type_combobox = QComboBox(self.annotate_layer_create_groupbox)
        self.layer_type_combobox.addItem("")
        self.layer_type_combobox.addItem("")
        self.layer_type_combobox.addItem("")
        self.layer_type_combobox.addItem("")
        self.layer_type_combobox.setObjectName(u"layer_type_combobox")
        self.layer_type_combobox.setMinimumSize(QSize(110, 25))
        self.layer_type_combobox.setMaximumSize(QSize(110, 25))
        self.layer_type_combobox.setMaxCount(15)
        self.layer_type_combobox.setSizeAdjustPolicy(QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.layer_type_combobox.setIconSize(QSize(14, 14))
        self.layer_type_combobox.setFrame(False)

        self.gridLayout.addWidget(self.layer_type_combobox, 0, 0, 1, 1, Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.label_suffix_lineedit = QLineEdit(self.annotate_layer_create_groupbox)
        self.label_suffix_lineedit.setObjectName(u"label_suffix_lineedit")
        self.label_suffix_lineedit.setMinimumSize(QSize(60, 25))
        self.label_suffix_lineedit.setMaximumSize(QSize(60, 25))
        self.label_suffix_lineedit.setInputMask(u"")
        self.label_suffix_lineedit.setText(u"")
        self.label_suffix_lineedit.setMaxLength(100)

        self.gridLayout.addWidget(self.label_suffix_lineedit, 0, 2, 1, 1, Qt.AlignmentFlag.AlignVCenter)

        self.label_list_combobox = QComboBox(self.annotate_layer_create_groupbox)
        self.label_list_combobox.addItem("")
        self.label_list_combobox.addItem("")
        self.label_list_combobox.addItem("")
        self.label_list_combobox.setObjectName(u"label_list_combobox")
        self.label_list_combobox.setMinimumSize(QSize(110, 25))
        self.label_list_combobox.setMaximumSize(QSize(110, 25))
        self.label_list_combobox.setEditable(False)
        self.label_list_combobox.setMaxCount(15)
        self.label_list_combobox.setSizeAdjustPolicy(QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.label_list_combobox.setIconSize(QSize(14, 14))
        self.label_list_combobox.setFrame(False)

        self.gridLayout.addWidget(self.label_list_combobox, 0, 1, 1, 1, Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.hard_reset_layer_btn = QPushButton(self.annotate_layer_create_groupbox)
        self.hard_reset_layer_btn.setObjectName(u"hard_reset_layer_btn")
        self.hard_reset_layer_btn.setMinimumSize(QSize(70, 25))
        self.hard_reset_layer_btn.setMaximumSize(QSize(70, 25))
        self.hard_reset_layer_btn.setAutoRepeatInterval(2000)

        self.gridLayout.addWidget(self.hard_reset_layer_btn, 1, 3, 1, 1, Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignVCenter)

        self.create_annotation_layer_btn = QPushButton(self.annotate_layer_create_groupbox)
        self.create_annotation_layer_btn.setObjectName(u"create_annotation_layer_btn")
        self.create_annotation_layer_btn.setMinimumSize(QSize(70, 25))
        self.create_annotation_layer_btn.setMaximumSize(QSize(70, 25))

        self.gridLayout.addWidget(self.create_annotation_layer_btn, 0, 3, 1, 1, Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignVCenter)


        self.annotate_vertical_layout.addWidget(self.annotate_layer_create_groupbox, 0, Qt.AlignmentFlag.AlignTop)

        self.annotate_param_groupbox = QGroupBox(self.verticalLayoutWidget_2)
        self.annotate_param_groupbox.setObjectName(u"annotate_param_groupbox")
        self.annotate_param_groupbox.setEnabled(False)
        sizePolicy3.setHeightForWidth(self.annotate_param_groupbox.sizePolicy().hasHeightForWidth())
        self.annotate_param_groupbox.setSizePolicy(sizePolicy3)
        self.annotate_param_groupbox.setMinimumSize(QSize(400, 60))
        self.annotate_param_groupbox.setMaximumSize(QSize(400, 60))
        self.horizontalLayout_4 = QHBoxLayout(self.annotate_param_groupbox)
        self.horizontalLayout_4.setSpacing(20)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(9, 9, 9, 9)
        self.kernel_label = QLabel(self.annotate_param_groupbox)
        self.kernel_label.setObjectName(u"kernel_label")
        sizePolicy4 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.kernel_label.sizePolicy().hasHeightForWidth())
        self.kernel_label.setSizePolicy(sizePolicy4)
        self.kernel_label.setMaximumSize(QSize(400, 25))

        self.horizontalLayout_4.addWidget(self.kernel_label, 0, Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.opening_kernel_radius_input = QSpinBox(self.annotate_param_groupbox)
        self.opening_kernel_radius_input.setObjectName(u"opening_kernel_radius_input")
        sizePolicy3.setHeightForWidth(self.opening_kernel_radius_input.sizePolicy().hasHeightForWidth())
        self.opening_kernel_radius_input.setSizePolicy(sizePolicy3)
        self.opening_kernel_radius_input.setMinimumSize(QSize(60, 25))
        self.opening_kernel_radius_input.setMaximumSize(QSize(60, 25))
        self.opening_kernel_radius_input.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.opening_kernel_radius_input.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.PlusMinus)
        self.opening_kernel_radius_input.setMaximum(20)
        self.opening_kernel_radius_input.setValue(5)

        self.horizontalLayout_4.addWidget(self.opening_kernel_radius_input, 0, Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignVCenter)


        self.annotate_vertical_layout.addWidget(self.annotate_param_groupbox)

        self.annotate_layer_predict_groupbox = QGroupBox(self.verticalLayoutWidget_2)
        self.annotate_layer_predict_groupbox.setObjectName(u"annotate_layer_predict_groupbox")
        sizePolicy3.setHeightForWidth(self.annotate_layer_predict_groupbox.sizePolicy().hasHeightForWidth())
        self.annotate_layer_predict_groupbox.setSizePolicy(sizePolicy3)
        self.annotate_layer_predict_groupbox.setMinimumSize(QSize(400, 60))
        self.annotate_layer_predict_groupbox.setMaximumSize(QSize(400, 60))
        self.horizontalLayout_2 = QHBoxLayout(self.annotate_layer_predict_groupbox)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.batch_predict_progressbar = QProgressBar(self.annotate_layer_predict_groupbox)
        self.batch_predict_progressbar.setObjectName(u"batch_predict_progressbar")
        sizePolicy5 = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.Fixed)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.batch_predict_progressbar.sizePolicy().hasHeightForWidth())
        self.batch_predict_progressbar.setSizePolicy(sizePolicy5)
        self.batch_predict_progressbar.setMinimumSize(QSize(130, 25))
        self.batch_predict_progressbar.setMaximumSize(QSize(130, 25))
        self.batch_predict_progressbar.setMaximum(20)
        self.batch_predict_progressbar.setValue(0)

        self.horizontalLayout_2.addWidget(self.batch_predict_progressbar, 0, Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.skip_label = QLabel(self.annotate_layer_predict_groupbox)
        self.skip_label.setObjectName(u"skip_label")
        self.skip_label.setMinimumSize(QSize(30, 25))
        self.skip_label.setMaximumSize(QSize(30, 25))
        self.skip_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout_2.addWidget(self.skip_label, 0, Qt.AlignmentFlag.AlignRight)

        self.skip_frames_spinbox = QSpinBox(self.annotate_layer_predict_groupbox)
        self.skip_frames_spinbox.setObjectName(u"skip_frames_spinbox")
        sizePolicy3.setHeightForWidth(self.skip_frames_spinbox.sizePolicy().hasHeightForWidth())
        self.skip_frames_spinbox.setSizePolicy(sizePolicy3)
        self.skip_frames_spinbox.setMinimumSize(QSize(35, 25))
        self.skip_frames_spinbox.setMaximumSize(QSize(35, 25))
        self.skip_frames_spinbox.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.skip_frames_spinbox.setMaximum(200)

        self.horizontalLayout_2.addWidget(self.skip_frames_spinbox)

        self.predict_next_oneframe_btn = QPushButton(self.annotate_layer_predict_groupbox)
        self.predict_next_oneframe_btn.setObjectName(u"predict_next_oneframe_btn")
        self.predict_next_oneframe_btn.setEnabled(False)
        sizePolicy3.setHeightForWidth(self.predict_next_oneframe_btn.sizePolicy().hasHeightForWidth())
        self.predict_next_oneframe_btn.setSizePolicy(sizePolicy3)
        self.predict_next_oneframe_btn.setMinimumSize(QSize(20, 25))
        self.predict_next_oneframe_btn.setMaximumSize(QSize(20, 25))
        self.predict_next_oneframe_btn.setBaseSize(QSize(15, 25))

        self.horizontalLayout_2.addWidget(self.predict_next_oneframe_btn)

        self.predict_next_batch_btn = QPushButton(self.annotate_layer_predict_groupbox)
        self.predict_next_batch_btn.setObjectName(u"predict_next_batch_btn")
        self.predict_next_batch_btn.setEnabled(False)
        self.predict_next_batch_btn.setMinimumSize(QSize(80, 25))
        self.predict_next_batch_btn.setMaximumSize(QSize(80, 25))

        self.horizontalLayout_2.addWidget(self.predict_next_batch_btn, 0, Qt.AlignmentFlag.AlignVCenter)


        self.annotate_vertical_layout.addWidget(self.annotate_layer_predict_groupbox, 0, Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignBottom)

        icon1 = QIcon()
        icon1.addFile(u"icons/noun-copywriting-7158879.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.toolBox.addItem(self.annotate_tab, icon1, u"Generate annotation data")
        self.train_tab = QWidget()
        self.train_tab.setObjectName(u"train_tab")
        self.train_tab.setGeometry(QRect(0, 0, 410, 414))
        sizePolicy1.setHeightForWidth(self.train_tab.sizePolicy().hasHeightForWidth())
        self.train_tab.setSizePolicy(sizePolicy1)
        self.verticalLayoutWidget_4 = QWidget(self.train_tab)
        self.verticalLayoutWidget_4.setObjectName(u"verticalLayoutWidget_4")
        self.verticalLayoutWidget_4.setGeometry(QRect(0, 0, 402, 371))
        self.train_vertical_layout = QVBoxLayout(self.verticalLayoutWidget_4)
        self.train_vertical_layout.setObjectName(u"train_vertical_layout")
        self.train_vertical_layout.setContentsMargins(0, 0, 0, 0)
        self.train_generate_groupbox = QGroupBox(self.verticalLayoutWidget_4)
        self.train_generate_groupbox.setObjectName(u"train_generate_groupbox")
        self.train_generate_groupbox.setEnabled(False)
        sizePolicy3.setHeightForWidth(self.train_generate_groupbox.sizePolicy().hasHeightForWidth())
        self.train_generate_groupbox.setSizePolicy(sizePolicy3)
        self.train_generate_groupbox.setMinimumSize(QSize(400, 160))
        self.train_generate_groupbox.setMaximumSize(QSize(400, 140))
        self.train_generate_groupbox.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.layoutWidget = QWidget(self.train_generate_groupbox)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(10, 30, 281, 29))
        self.train_progress_A_horizontalLayout = QHBoxLayout(self.layoutWidget)
        self.train_progress_A_horizontalLayout.setObjectName(u"train_progress_A_horizontalLayout")
        self.train_progress_A_horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.train_polygons_overall_progressbar = QProgressBar(self.layoutWidget)
        self.train_polygons_overall_progressbar.setObjectName(u"train_polygons_overall_progressbar")
        self.train_polygons_overall_progressbar.setEnabled(False)
        sizePolicy5.setHeightForWidth(self.train_polygons_overall_progressbar.sizePolicy().hasHeightForWidth())
        self.train_polygons_overall_progressbar.setSizePolicy(sizePolicy5)
        self.train_polygons_overall_progressbar.setMinimumSize(QSize(50, 25))
        self.train_polygons_overall_progressbar.setMaximumSize(QSize(50, 25))
        self.train_polygons_overall_progressbar.setMaximum(20)
        self.train_polygons_overall_progressbar.setValue(0)

        self.train_progress_A_horizontalLayout.addWidget(self.train_polygons_overall_progressbar)

        self.train_polygons_frames_progressbar = QProgressBar(self.layoutWidget)
        self.train_polygons_frames_progressbar.setObjectName(u"train_polygons_frames_progressbar")
        self.train_polygons_frames_progressbar.setEnabled(False)
        sizePolicy5.setHeightForWidth(self.train_polygons_frames_progressbar.sizePolicy().hasHeightForWidth())
        self.train_polygons_frames_progressbar.setSizePolicy(sizePolicy5)
        self.train_polygons_frames_progressbar.setMinimumSize(QSize(100, 25))
        self.train_polygons_frames_progressbar.setMaximumSize(QSize(100, 25))
        self.train_polygons_frames_progressbar.setMaximum(20)
        self.train_polygons_frames_progressbar.setValue(0)

        self.train_progress_A_horizontalLayout.addWidget(self.train_polygons_frames_progressbar)

        self.train_polygons_label = QLabel(self.layoutWidget)
        self.train_polygons_label.setObjectName(u"train_polygons_label")
        self.train_polygons_label.setEnabled(False)
        self.train_polygons_label.setMinimumSize(QSize(0, 25))
        self.train_polygons_label.setMaximumSize(QSize(16777215, 25))

        self.train_progress_A_horizontalLayout.addWidget(self.train_polygons_label)

        self.layoutWidget1 = QWidget(self.train_generate_groupbox)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(10, 60, 281, 29))
        self.train_progress_B_horizontalLayout = QHBoxLayout(self.layoutWidget1)
        self.train_progress_B_horizontalLayout.setObjectName(u"train_progress_B_horizontalLayout")
        self.train_progress_B_horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.train_export_overall_progressbar = QProgressBar(self.layoutWidget1)
        self.train_export_overall_progressbar.setObjectName(u"train_export_overall_progressbar")
        self.train_export_overall_progressbar.setEnabled(False)
        sizePolicy5.setHeightForWidth(self.train_export_overall_progressbar.sizePolicy().hasHeightForWidth())
        self.train_export_overall_progressbar.setSizePolicy(sizePolicy5)
        self.train_export_overall_progressbar.setMinimumSize(QSize(50, 25))
        self.train_export_overall_progressbar.setMaximumSize(QSize(50, 25))
        self.train_export_overall_progressbar.setMaximum(20)
        self.train_export_overall_progressbar.setValue(0)

        self.train_progress_B_horizontalLayout.addWidget(self.train_export_overall_progressbar)

        self.train_export_frames_progressbar = QProgressBar(self.layoutWidget1)
        self.train_export_frames_progressbar.setObjectName(u"train_export_frames_progressbar")
        self.train_export_frames_progressbar.setEnabled(False)
        sizePolicy5.setHeightForWidth(self.train_export_frames_progressbar.sizePolicy().hasHeightForWidth())
        self.train_export_frames_progressbar.setSizePolicy(sizePolicy5)
        self.train_export_frames_progressbar.setMinimumSize(QSize(100, 25))
        self.train_export_frames_progressbar.setMaximumSize(QSize(100, 25))
        self.train_export_frames_progressbar.setMaximum(20)
        self.train_export_frames_progressbar.setValue(0)

        self.train_progress_B_horizontalLayout.addWidget(self.train_export_frames_progressbar)

        self.train_export_label = QLabel(self.layoutWidget1)
        self.train_export_label.setObjectName(u"train_export_label")
        self.train_export_label.setEnabled(False)
        self.train_export_label.setMinimumSize(QSize(0, 25))
        self.train_export_label.setMaximumSize(QSize(16777215, 25))

        self.train_progress_B_horizontalLayout.addWidget(self.train_export_label)

        self.layoutWidget2 = QWidget(self.train_generate_groupbox)
        self.layoutWidget2.setObjectName(u"layoutWidget2")
        self.layoutWidget2.setGeometry(QRect(300, 30, 90, 81))
        self.train_checkboxes_verticalLayout = QVBoxLayout(self.layoutWidget2)
        self.train_checkboxes_verticalLayout.setSpacing(10)
        self.train_checkboxes_verticalLayout.setObjectName(u"train_checkboxes_verticalLayout")
        self.train_checkboxes_verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.train_prune_checkBox = QCheckBox(self.layoutWidget2)
        self.train_prune_checkBox.setObjectName(u"train_prune_checkBox")
        self.train_prune_checkBox.setEnabled(False)
        self.train_prune_checkBox.setMinimumSize(QSize(90, 25))
        self.train_prune_checkBox.setMaximumSize(QSize(90, 25))
        self.train_prune_checkBox.setChecked(True)

        self.train_checkboxes_verticalLayout.addWidget(self.train_prune_checkBox)

        self.train_data_watershed_checkBox = QCheckBox(self.layoutWidget2)
        self.train_data_watershed_checkBox.setObjectName(u"train_data_watershed_checkBox")
        self.train_data_watershed_checkBox.setEnabled(False)
        self.train_data_watershed_checkBox.setMinimumSize(QSize(90, 25))
        self.train_data_watershed_checkBox.setMaximumSize(QSize(90, 25))
        self.train_data_watershed_checkBox.setChecked(False)

        self.train_checkboxes_verticalLayout.addWidget(self.train_data_watershed_checkBox)

        self.train_data_overwrite_checkBox = QCheckBox(self.layoutWidget2)
        self.train_data_overwrite_checkBox.setObjectName(u"train_data_overwrite_checkBox")
        self.train_data_overwrite_checkBox.setEnabled(False)
        self.train_data_overwrite_checkBox.setMinimumSize(QSize(90, 25))
        self.train_data_overwrite_checkBox.setMaximumSize(QSize(90, 25))
        self.train_data_overwrite_checkBox.setChecked(True)

        self.train_checkboxes_verticalLayout.addWidget(self.train_data_overwrite_checkBox)

        self.layoutWidget3 = QWidget(self.train_generate_groupbox)
        self.layoutWidget3.setObjectName(u"layoutWidget3")
        self.layoutWidget3.setGeometry(QRect(10, 120, 381, 37))
        self.train_folder_btn_horizontalLayout = QHBoxLayout(self.layoutWidget3)
        self.train_folder_btn_horizontalLayout.setObjectName(u"train_folder_btn_horizontalLayout")
        self.train_folder_btn_horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.training_data_folder_label = QLabel(self.layoutWidget3)
        self.training_data_folder_label.setObjectName(u"training_data_folder_label")
        self.training_data_folder_label.setEnabled(False)
        self.training_data_folder_label.setMinimumSize(QSize(275, 25))
        self.training_data_folder_label.setMaximumSize(QSize(275, 25))

        self.train_folder_btn_horizontalLayout.addWidget(self.training_data_folder_label)

        self.generate_training_data_btn = QPushButton(self.layoutWidget3)
        self.generate_training_data_btn.setObjectName(u"generate_training_data_btn")
        sizePolicy3.setHeightForWidth(self.generate_training_data_btn.sizePolicy().hasHeightForWidth())
        self.generate_training_data_btn.setSizePolicy(sizePolicy3)
        self.generate_training_data_btn.setMinimumSize(QSize(90, 25))
        self.generate_training_data_btn.setMaximumSize(QSize(90, 25))

        self.train_folder_btn_horizontalLayout.addWidget(self.generate_training_data_btn, 0, Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignVCenter)


        self.train_vertical_layout.addWidget(self.train_generate_groupbox, 0, Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignTop)

        self.train_train_groupbox = QGroupBox(self.verticalLayoutWidget_4)
        self.train_train_groupbox.setObjectName(u"train_train_groupbox")
        self.train_train_groupbox.setEnabled(False)
        sizePolicy3.setHeightForWidth(self.train_train_groupbox.sizePolicy().hasHeightForWidth())
        self.train_train_groupbox.setSizePolicy(sizePolicy3)
        self.train_train_groupbox.setMinimumSize(QSize(400, 185))
        self.train_train_groupbox.setMaximumSize(QSize(400, 185))
        self.train_train_groupbox.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.layoutWidget4 = QWidget(self.train_train_groupbox)
        self.layoutWidget4.setObjectName(u"layoutWidget4")
        self.layoutWidget4.setGeometry(QRect(10, 70, 201, 62))
        self.train_grid_layout = QGridLayout(self.layoutWidget4)
        self.train_grid_layout.setObjectName(u"train_grid_layout")
        self.train_grid_layout.setContentsMargins(0, 0, 10, 0)
        self.num_epochs_label = QLabel(self.layoutWidget4)
        self.num_epochs_label.setObjectName(u"num_epochs_label")
        sizePolicy4.setHeightForWidth(self.num_epochs_label.sizePolicy().hasHeightForWidth())
        self.num_epochs_label.setSizePolicy(sizePolicy4)
        self.num_epochs_label.setMinimumSize(QSize(100, 0))
        self.num_epochs_label.setMaximumSize(QSize(100, 25))

        self.train_grid_layout.addWidget(self.num_epochs_label, 0, 0, 1, 1, Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.save_period_label = QLabel(self.layoutWidget4)
        self.save_period_label.setObjectName(u"save_period_label")
        sizePolicy4.setHeightForWidth(self.save_period_label.sizePolicy().hasHeightForWidth())
        self.save_period_label.setSizePolicy(sizePolicy4)
        self.save_period_label.setMinimumSize(QSize(100, 0))
        self.save_period_label.setMaximumSize(QSize(100, 25))

        self.train_grid_layout.addWidget(self.save_period_label, 1, 0, 1, 1, Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.num_epochs_input = QSpinBox(self.layoutWidget4)
        self.num_epochs_input.setObjectName(u"num_epochs_input")
        sizePolicy3.setHeightForWidth(self.num_epochs_input.sizePolicy().hasHeightForWidth())
        self.num_epochs_input.setSizePolicy(sizePolicy3)
        self.num_epochs_input.setMinimumSize(QSize(80, 25))
        self.num_epochs_input.setMaximumSize(QSize(80, 25))
        self.num_epochs_input.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.num_epochs_input.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.PlusMinus)
        self.num_epochs_input.setMinimum(1)
        self.num_epochs_input.setMaximum(900)
        self.num_epochs_input.setSingleStep(10)
        self.num_epochs_input.setValue(250)

        self.train_grid_layout.addWidget(self.num_epochs_input, 0, 1, 1, 1, Qt.AlignmentFlag.AlignRight)

        self.save_period_input = QSpinBox(self.layoutWidget4)
        self.save_period_input.setObjectName(u"save_period_input")
        sizePolicy3.setHeightForWidth(self.save_period_input.sizePolicy().hasHeightForWidth())
        self.save_period_input.setSizePolicy(sizePolicy3)
        self.save_period_input.setMinimumSize(QSize(80, 25))
        self.save_period_input.setMaximumSize(QSize(80, 25))
        self.save_period_input.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.save_period_input.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.PlusMinus)
        self.save_period_input.setMinimum(2)
        self.save_period_input.setMaximum(100)
        self.save_period_input.setSingleStep(15)
        self.save_period_input.setValue(50)

        self.train_grid_layout.addWidget(self.save_period_input, 1, 1, 1, 1, Qt.AlignmentFlag.AlignRight)

        self.layoutWidget5 = QWidget(self.train_train_groupbox)
        self.layoutWidget5.setObjectName(u"layoutWidget5")
        self.layoutWidget5.setGeometry(QRect(300, 30, 90, 81))
        self.train_verticalLayout = QVBoxLayout(self.layoutWidget5)
        self.train_verticalLayout.setSpacing(10)
        self.train_verticalLayout.setObjectName(u"train_verticalLayout")
        self.train_verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.train_resume_checkBox = QCheckBox(self.layoutWidget5)
        self.train_resume_checkBox.setObjectName(u"train_resume_checkBox")
        self.train_resume_checkBox.setEnabled(False)
        self.train_resume_checkBox.setMinimumSize(QSize(90, 25))
        self.train_resume_checkBox.setMaximumSize(QSize(90, 25))

        self.train_verticalLayout.addWidget(self.train_resume_checkBox, 0, Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)

        self.train_training_overwrite_checkBox = QCheckBox(self.layoutWidget5)
        self.train_training_overwrite_checkBox.setObjectName(u"train_training_overwrite_checkBox")
        self.train_training_overwrite_checkBox.setEnabled(False)
        self.train_training_overwrite_checkBox.setMinimumSize(QSize(90, 25))
        self.train_training_overwrite_checkBox.setMaximumSize(QSize(90, 25))
        self.train_training_overwrite_checkBox.setChecked(True)

        self.train_verticalLayout.addWidget(self.train_training_overwrite_checkBox, 0, Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)

        self.launch_tensorboard_checkBox = QCheckBox(self.layoutWidget5)
        self.launch_tensorboard_checkBox.setObjectName(u"launch_tensorboard_checkBox")
        self.launch_tensorboard_checkBox.setEnabled(False)
        self.launch_tensorboard_checkBox.setMinimumSize(QSize(90, 25))
        self.launch_tensorboard_checkBox.setMaximumSize(QSize(90, 25))
        self.launch_tensorboard_checkBox.setChecked(True)

        self.train_verticalLayout.addWidget(self.launch_tensorboard_checkBox)

        self.layoutWidget6 = QWidget(self.train_train_groupbox)
        self.layoutWidget6.setObjectName(u"layoutWidget6")
        self.layoutWidget6.setGeometry(QRect(10, 30, 281, 31))
        self.model_choose_horizontalLayout = QHBoxLayout(self.layoutWidget6)
        self.model_choose_horizontalLayout.setObjectName(u"model_choose_horizontalLayout")
        self.model_choose_horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.yolomodel_list = QComboBox(self.layoutWidget6)
        self.yolomodel_list.addItem("")
        self.yolomodel_list.setObjectName(u"yolomodel_list")
        self.yolomodel_list.setMinimumSize(QSize(150, 25))
        self.yolomodel_list.setMaximumSize(QSize(150, 25))

        self.model_choose_horizontalLayout.addWidget(self.yolomodel_list, 0, Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.yoloimagesize_list = QComboBox(self.layoutWidget6)
        self.yoloimagesize_list.addItem("")
        self.yoloimagesize_list.addItem("")
        self.yoloimagesize_list.addItem("")
        self.yoloimagesize_list.setObjectName(u"yoloimagesize_list")
        self.yoloimagesize_list.setMinimumSize(QSize(100, 25))
        self.yoloimagesize_list.setMaximumSize(QSize(100, 25))

        self.model_choose_horizontalLayout.addWidget(self.yoloimagesize_list, 0, Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.layoutWidget7 = QWidget(self.train_train_groupbox)
        self.layoutWidget7.setObjectName(u"layoutWidget7")
        self.layoutWidget7.setGeometry(QRect(10, 140, 380, 37))
        self.epochs_horizontalLayout = QHBoxLayout(self.layoutWidget7)
        self.epochs_horizontalLayout.setObjectName(u"epochs_horizontalLayout")
        self.epochs_horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.train_epochs_progressbar = QProgressBar(self.layoutWidget7)
        self.train_epochs_progressbar.setObjectName(u"train_epochs_progressbar")
        self.train_epochs_progressbar.setEnabled(False)
        sizePolicy5.setHeightForWidth(self.train_epochs_progressbar.sizePolicy().hasHeightForWidth())
        self.train_epochs_progressbar.setSizePolicy(sizePolicy5)
        self.train_epochs_progressbar.setMinimumSize(QSize(120, 25))
        self.train_epochs_progressbar.setMaximumSize(QSize(120, 25))
        self.train_epochs_progressbar.setMaximum(20)
        self.train_epochs_progressbar.setValue(0)

        self.epochs_horizontalLayout.addWidget(self.train_epochs_progressbar, 0, Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.train_finishtime_label = QLabel(self.layoutWidget7)
        self.train_finishtime_label.setObjectName(u"train_finishtime_label")
        self.train_finishtime_label.setEnabled(False)
        self.train_finishtime_label.setMinimumSize(QSize(150, 25))
        self.train_finishtime_label.setMaximumSize(QSize(150, 25))

        self.epochs_horizontalLayout.addWidget(self.train_finishtime_label, 0, Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.start_stop_training_btn = QPushButton(self.layoutWidget7)
        self.start_stop_training_btn.setObjectName(u"start_stop_training_btn")
        sizePolicy3.setHeightForWidth(self.start_stop_training_btn.sizePolicy().hasHeightForWidth())
        self.start_stop_training_btn.setSizePolicy(sizePolicy3)
        self.start_stop_training_btn.setMinimumSize(QSize(90, 25))
        self.start_stop_training_btn.setMaximumSize(QSize(90, 25))

        self.epochs_horizontalLayout.addWidget(self.start_stop_training_btn, 0, Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignVCenter)


        self.train_vertical_layout.addWidget(self.train_train_groupbox)

        icon2 = QIcon()
        icon2.addFile(u"icons/noun-rocket-7158872.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.toolBox.addItem(self.train_tab, icon2, u"Train model")
        self.predict_tab = QWidget()
        self.predict_tab.setObjectName(u"predict_tab")
        self.predict_tab.setGeometry(QRect(0, 0, 410, 414))
        sizePolicy1.setHeightForWidth(self.predict_tab.sizePolicy().hasHeightForWidth())
        self.predict_tab.setSizePolicy(sizePolicy1)
        self.verticalLayoutWidget_5 = QWidget(self.predict_tab)
        self.verticalLayoutWidget_5.setObjectName(u"verticalLayoutWidget_5")
        self.verticalLayoutWidget_5.setGeometry(QRect(0, 0, 402, 409))
        self.predict_verticalLayout = QVBoxLayout(self.verticalLayoutWidget_5)
        self.predict_verticalLayout.setSpacing(20)
        self.predict_verticalLayout.setObjectName(u"predict_verticalLayout")
        self.predict_verticalLayout.setContentsMargins(0, 0, 0, 10)
        self.predict_video_drop_groupbox = QGroupBox(self.verticalLayoutWidget_5)
        self.predict_video_drop_groupbox.setObjectName(u"predict_video_drop_groupbox")
        self.predict_video_drop_groupbox.setEnabled(True)
        sizePolicy2.setHeightForWidth(self.predict_video_drop_groupbox.sizePolicy().hasHeightForWidth())
        self.predict_video_drop_groupbox.setSizePolicy(sizePolicy2)
        self.predict_video_drop_groupbox.setMinimumSize(QSize(400, 100))
        self.predict_video_drop_groupbox.setMaximumSize(QSize(400, 100))
        self.horizontalLayout_3 = QHBoxLayout(self.predict_video_drop_groupbox)
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(9, 9, 9, 9)
        self.predict_video_drop_widget = QWidget(self.predict_video_drop_groupbox)
        self.predict_video_drop_widget.setObjectName(u"predict_video_drop_widget")
        self.predict_video_drop_widget.setMinimumSize(QSize(380, 60))
        self.predict_video_drop_widget.setMaximumSize(QSize(380, 60))

        self.horizontalLayout_3.addWidget(self.predict_video_drop_widget)


        self.predict_verticalLayout.addWidget(self.predict_video_drop_groupbox)

        self.predict_video_predict_groupbox = QGroupBox(self.verticalLayoutWidget_5)
        self.predict_video_predict_groupbox.setObjectName(u"predict_video_predict_groupbox")
        self.predict_video_predict_groupbox.setEnabled(True)
        sizePolicy2.setHeightForWidth(self.predict_video_predict_groupbox.sizePolicy().hasHeightForWidth())
        self.predict_video_predict_groupbox.setSizePolicy(sizePolicy2)
        self.predict_video_predict_groupbox.setMinimumSize(QSize(400, 280))
        self.predict_video_predict_groupbox.setMaximumSize(QSize(400, 280))
        self.layoutWidget_2 = QWidget(self.predict_video_predict_groupbox)
        self.layoutWidget_2.setObjectName(u"layoutWidget_2")
        self.layoutWidget_2.setGeometry(QRect(11, 193, 387, 29))
        self.predict_progress_bar_layout = QHBoxLayout(self.layoutWidget_2)
        self.predict_progress_bar_layout.setObjectName(u"predict_progress_bar_layout")
        self.predict_progress_bar_layout.setContentsMargins(0, 0, 0, 0)
        self.predict_overall_progressbar = QProgressBar(self.layoutWidget_2)
        self.predict_overall_progressbar.setObjectName(u"predict_overall_progressbar")
        self.predict_overall_progressbar.setEnabled(False)
        sizePolicy5.setHeightForWidth(self.predict_overall_progressbar.sizePolicy().hasHeightForWidth())
        self.predict_overall_progressbar.setSizePolicy(sizePolicy5)
        self.predict_overall_progressbar.setMinimumSize(QSize(50, 25))
        self.predict_overall_progressbar.setMaximumSize(QSize(50, 25))
        self.predict_overall_progressbar.setMaximum(20)
        self.predict_overall_progressbar.setValue(0)

        self.predict_progress_bar_layout.addWidget(self.predict_overall_progressbar, 0, Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.predict_current_video_progressbar = QProgressBar(self.layoutWidget_2)
        self.predict_current_video_progressbar.setObjectName(u"predict_current_video_progressbar")
        self.predict_current_video_progressbar.setEnabled(False)
        sizePolicy5.setHeightForWidth(self.predict_current_video_progressbar.sizePolicy().hasHeightForWidth())
        self.predict_current_video_progressbar.setSizePolicy(sizePolicy5)
        self.predict_current_video_progressbar.setMinimumSize(QSize(120, 25))
        self.predict_current_video_progressbar.setMaximumSize(QSize(120, 25))
        self.predict_current_video_progressbar.setMaximum(20)
        self.predict_current_video_progressbar.setValue(0)

        self.predict_progress_bar_layout.addWidget(self.predict_current_video_progressbar, 0, Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.predict_current_videoname_label = QLabel(self.layoutWidget_2)
        self.predict_current_videoname_label.setObjectName(u"predict_current_videoname_label")
        self.predict_current_videoname_label.setEnabled(False)
        self.predict_current_videoname_label.setMinimumSize(QSize(195, 25))
        self.predict_current_videoname_label.setMaximumSize(QSize(195, 25))

        self.predict_progress_bar_layout.addWidget(self.predict_current_videoname_label)

        self.layoutWidget_3 = QWidget(self.predict_video_predict_groupbox)
        self.layoutWidget_3.setObjectName(u"layoutWidget_3")
        self.layoutWidget_3.setGeometry(QRect(11, 232, 381, 27))
        self.predict_finish_time_layout = QHBoxLayout(self.layoutWidget_3)
        self.predict_finish_time_layout.setObjectName(u"predict_finish_time_layout")
        self.predict_finish_time_layout.setContentsMargins(0, 0, 0, 0)
        self.predict_finish_time_label = QLabel(self.layoutWidget_3)
        self.predict_finish_time_label.setObjectName(u"predict_finish_time_label")
        self.predict_finish_time_label.setEnabled(False)
        self.predict_finish_time_label.setMinimumSize(QSize(0, 25))
        self.predict_finish_time_label.setMaximumSize(QSize(16777215, 25))

        self.predict_finish_time_layout.addWidget(self.predict_finish_time_label, 0, Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.layoutWidget8 = QWidget(self.predict_video_predict_groupbox)
        self.layoutWidget8.setObjectName(u"layoutWidget8")
        self.layoutWidget8.setGeometry(QRect(10, 120, 381, 73))
        self.predict_grid_layout2 = QGridLayout(self.layoutWidget8)
        self.predict_grid_layout2.setObjectName(u"predict_grid_layout2")
        self.predict_grid_layout2.setContentsMargins(0, 0, 0, 0)
        self.prediction_iou_label = QLabel(self.layoutWidget8)
        self.prediction_iou_label.setObjectName(u"prediction_iou_label")
        sizePolicy4.setHeightForWidth(self.prediction_iou_label.sizePolicy().hasHeightForWidth())
        self.prediction_iou_label.setSizePolicy(sizePolicy4)
        self.prediction_iou_label.setMinimumSize(QSize(40, 0))
        self.prediction_iou_label.setMaximumSize(QSize(40, 25))
        self.prediction_iou_label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.predict_grid_layout2.addWidget(self.prediction_iou_label, 0, 2, 1, 1, Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignBottom)

        self.predict_start_btn = QPushButton(self.layoutWidget8)
        self.predict_start_btn.setObjectName(u"predict_start_btn")
        self.predict_start_btn.setMinimumSize(QSize(90, 25))
        self.predict_start_btn.setMaximumSize(QSize(90, 25))

        self.predict_grid_layout2.addWidget(self.predict_start_btn, 1, 3, 1, 1, Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTop)

        self.prediction_poly_sigma_label = QLabel(self.layoutWidget8)
        self.prediction_poly_sigma_label.setObjectName(u"prediction_poly_sigma_label")
        sizePolicy4.setHeightForWidth(self.prediction_poly_sigma_label.sizePolicy().hasHeightForWidth())
        self.prediction_poly_sigma_label.setSizePolicy(sizePolicy4)
        self.prediction_poly_sigma_label.setMinimumSize(QSize(100, 0))
        self.prediction_poly_sigma_label.setMaximumSize(QSize(100, 25))

        self.predict_grid_layout2.addWidget(self.prediction_poly_sigma_label, 0, 0, 1, 1, Qt.AlignmentFlag.AlignBottom)

        self.prediction_conf_thresh_label = QLabel(self.layoutWidget8)
        self.prediction_conf_thresh_label.setObjectName(u"prediction_conf_thresh_label")
        sizePolicy4.setHeightForWidth(self.prediction_conf_thresh_label.sizePolicy().hasHeightForWidth())
        self.prediction_conf_thresh_label.setSizePolicy(sizePolicy4)
        self.prediction_conf_thresh_label.setMinimumSize(QSize(100, 0))
        self.prediction_conf_thresh_label.setMaximumSize(QSize(100, 25))

        self.predict_grid_layout2.addWidget(self.prediction_conf_thresh_label, 1, 0, 1, 1, Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)

        self.predict_polygo_sigma_spinbox = QDoubleSpinBox(self.layoutWidget8)
        self.predict_polygo_sigma_spinbox.setObjectName(u"predict_polygo_sigma_spinbox")
        self.predict_polygo_sigma_spinbox.setMinimumSize(QSize(90, 25))
        self.predict_polygo_sigma_spinbox.setMaximumSize(QSize(90, 25))
        self.predict_polygo_sigma_spinbox.setDecimals(1)
        self.predict_polygo_sigma_spinbox.setMaximum(5.000000000000000)
        self.predict_polygo_sigma_spinbox.setSingleStep(0.100000000000000)
        self.predict_polygo_sigma_spinbox.setValue(0.000000000000000)

        self.predict_grid_layout2.addWidget(self.predict_polygo_sigma_spinbox, 0, 1, 1, 1, Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignBottom)

        self.predict_conf_thresh_spinbox = QDoubleSpinBox(self.layoutWidget8)
        self.predict_conf_thresh_spinbox.setObjectName(u"predict_conf_thresh_spinbox")
        self.predict_conf_thresh_spinbox.setMinimumSize(QSize(90, 25))
        self.predict_conf_thresh_spinbox.setMaximumSize(QSize(90, 25))
        self.predict_conf_thresh_spinbox.setMaximum(1.000000000000000)
        self.predict_conf_thresh_spinbox.setSingleStep(0.050000000000000)
        self.predict_conf_thresh_spinbox.setValue(0.850000000000000)

        self.predict_grid_layout2.addWidget(self.predict_conf_thresh_spinbox, 1, 1, 1, 1, Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)

        self.predict_iou_thresh_spinbox = QDoubleSpinBox(self.layoutWidget8)
        self.predict_iou_thresh_spinbox.setObjectName(u"predict_iou_thresh_spinbox")
        self.predict_iou_thresh_spinbox.setMinimumSize(QSize(90, 25))
        self.predict_iou_thresh_spinbox.setMaximumSize(QSize(90, 25))
        self.predict_iou_thresh_spinbox.setMaximum(1.000000000000000)
        self.predict_iou_thresh_spinbox.setSingleStep(0.100000000000000)
        self.predict_iou_thresh_spinbox.setValue(0.600000000000000)

        self.predict_grid_layout2.addWidget(self.predict_iou_thresh_spinbox, 0, 3, 1, 1, Qt.AlignmentFlag.AlignBottom)

        self.layoutWidget9 = QWidget(self.predict_video_predict_groupbox)
        self.layoutWidget9.setObjectName(u"layoutWidget9")
        self.layoutWidget9.setGeometry(QRect(10, 30, 381, 86))
        self.gridLayout_2 = QGridLayout(self.layoutWidget9)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 10)
        self.yolomodel_trained_list = QComboBox(self.layoutWidget9)
        self.yolomodel_trained_list.addItem("")
        self.yolomodel_trained_list.setObjectName(u"yolomodel_trained_list")
        self.yolomodel_trained_list.setEnabled(True)
        self.yolomodel_trained_list.setMinimumSize(QSize(150, 25))
        self.yolomodel_trained_list.setMaximumSize(QSize(150, 25))

        self.gridLayout_2.addWidget(self.yolomodel_trained_list, 0, 0, 2, 1, Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)

        self.yolomodel_tracker_list = QComboBox(self.layoutWidget9)
        self.yolomodel_tracker_list.addItem("")
        self.yolomodel_tracker_list.addItem("")
        self.yolomodel_tracker_list.addItem("")
        self.yolomodel_tracker_list.setObjectName(u"yolomodel_tracker_list")
        self.yolomodel_tracker_list.setMinimumSize(QSize(110, 25))
        self.yolomodel_tracker_list.setMaximumSize(QSize(110, 25))

        self.gridLayout_2.addWidget(self.yolomodel_tracker_list, 0, 1, 2, 1, Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)

        self.open_when_finish_checkBox = QCheckBox(self.layoutWidget9)
        self.open_when_finish_checkBox.setObjectName(u"open_when_finish_checkBox")
        self.open_when_finish_checkBox.setMinimumSize(QSize(90, 25))
        self.open_when_finish_checkBox.setMaximumSize(QSize(100, 25))
        self.open_when_finish_checkBox.setChecked(True)

        self.gridLayout_2.addWidget(self.open_when_finish_checkBox, 0, 2, 1, 1, Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)

        self.single_subject_checkBox = QCheckBox(self.layoutWidget9)
        self.single_subject_checkBox.setObjectName(u"single_subject_checkBox")
        self.single_subject_checkBox.setEnabled(True)
        self.single_subject_checkBox.setMinimumSize(QSize(90, 25))
        self.single_subject_checkBox.setMaximumSize(QSize(100, 25))
        self.single_subject_checkBox.setChecked(False)

        self.gridLayout_2.addWidget(self.single_subject_checkBox, 1, 2, 1, 1, Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)

        self.videos_for_prediction_list = QComboBox(self.layoutWidget9)
        self.videos_for_prediction_list.addItem("")
        self.videos_for_prediction_list.addItem("")
        self.videos_for_prediction_list.setObjectName(u"videos_for_prediction_list")
        self.videos_for_prediction_list.setMinimumSize(QSize(270, 25))
        self.videos_for_prediction_list.setMaximumSize(QSize(270, 25))
        self.videos_for_prediction_list.setEditable(False)
        self.videos_for_prediction_list.setMaxCount(15)
        self.videos_for_prediction_list.setSizeAdjustPolicy(QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.videos_for_prediction_list.setIconSize(QSize(14, 14))
        self.videos_for_prediction_list.setFrame(False)

        self.gridLayout_2.addWidget(self.videos_for_prediction_list, 2, 0, 1, 2, Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)

        self.overwrite_prediction_checkBox = QCheckBox(self.layoutWidget9)
        self.overwrite_prediction_checkBox.setObjectName(u"overwrite_prediction_checkBox")
        self.overwrite_prediction_checkBox.setEnabled(False)
        self.overwrite_prediction_checkBox.setMinimumSize(QSize(90, 25))
        self.overwrite_prediction_checkBox.setMaximumSize(QSize(100, 25))
        self.overwrite_prediction_checkBox.setChecked(True)

        self.gridLayout_2.addWidget(self.overwrite_prediction_checkBox, 2, 2, 1, 1, Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)


        self.predict_verticalLayout.addWidget(self.predict_video_predict_groupbox)

        icon3 = QIcon()
        icon3.addFile(u"icons/noun-conversion-7158876.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.toolBox.addItem(self.predict_tab, icon3, u"Analyze (new) videos")

        self.mainLayout.addWidget(self.toolBox)

        self.toolBox.raise_()
        self.octron_logo.raise_()

        self.retranslateUi(octron_widgetui)

        self.toolBox.setCurrentIndex(0)
        self.toolBox.layout().setSpacing(10)


        QMetaObject.connectSlotsByName(octron_widgetui)
    # setupUi

    def retranslateUi(self, octron_widgetui):
        octron_widgetui.setWindowTitle(QCoreApplication.translate("octron_widgetui", u"octron_gui", None))
        self.octron_logo.setText("")
        self.folder_sect_groupbox.setTitle(QCoreApplication.translate("octron_widgetui", u"Project folder", None))
        self.create_project_btn.setText(QCoreApplication.translate("octron_widgetui", u"\u2295 Choose", None))
        self.project_folder_path_label.setText(QCoreApplication.translate("octron_widgetui", u"Project folder path", None))
        self.project_video_drop_groupbox.setTitle(QCoreApplication.translate("octron_widgetui", u"Add new video file", None))
#if QT_CONFIG(tooltip)
        self.video_file_drop_widget.setToolTip(QCoreApplication.translate("octron_widgetui", u"Drag and drop one .mp4 file here", None))
#endif // QT_CONFIG(tooltip)
        self.project_existing_data_groupbox.setTitle(QCoreApplication.translate("octron_widgetui", u"Existing data", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.project_tab), QCoreApplication.translate("octron_widgetui", u"Manage project", None))
#if QT_CONFIG(tooltip)
        self.toolBox.setItemToolTip(self.toolBox.indexOf(self.project_tab), QCoreApplication.translate("octron_widgetui", u"Create new octron projects or load existing ones", None))
#endif // QT_CONFIG(tooltip)
        self.horizontalGroupBox.setTitle(QCoreApplication.translate("octron_widgetui", u"Model selection", None))
        self.sam2model_list.setItemText(0, QCoreApplication.translate("octron_widgetui", u"Choose model ...", None))

        self.load_sam2model_btn.setText(QCoreApplication.translate("octron_widgetui", u"Load model", None))
        self.annotate_layer_create_groupbox.setTitle(QCoreApplication.translate("octron_widgetui", u"Layer controls", None))
#if QT_CONFIG(tooltip)
        self.create_projection_layer_btn.setToolTip(QCoreApplication.translate("octron_widgetui", u"Create an average projection out of all segmented images for the current label", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.create_projection_layer_btn.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.create_projection_layer_btn.setText(QCoreApplication.translate("octron_widgetui", u"Visualize all", None))
        self.layer_type_combobox.setItemText(0, QCoreApplication.translate("octron_widgetui", u"Type ... ", None))
        self.layer_type_combobox.setItemText(1, QCoreApplication.translate("octron_widgetui", u"Shapes", None))
        self.layer_type_combobox.setItemText(2, QCoreApplication.translate("octron_widgetui", u"Points", None))
        self.layer_type_combobox.setItemText(3, QCoreApplication.translate("octron_widgetui", u"Anchors", None))

        self.layer_type_combobox.setCurrentText(QCoreApplication.translate("octron_widgetui", u"Type ... ", None))
#if QT_CONFIG(tooltip)
        self.label_suffix_lineedit.setToolTip(QCoreApplication.translate("octron_widgetui", u"The suffix disambiguates label layers from each other\n"
"that have the same label name.\n"
"For example:\n"
"The label could be octo and suffix 1 for the first octopus,\n"
"and octo and suffix 2 for the second octo ", None))
#endif // QT_CONFIG(tooltip)
        self.label_suffix_lineedit.setPlaceholderText(QCoreApplication.translate("octron_widgetui", u"Suffix", None))
        self.label_list_combobox.setItemText(0, QCoreApplication.translate("octron_widgetui", u"Label ... ", None))
        self.label_list_combobox.setItemText(1, QCoreApplication.translate("octron_widgetui", u"\u2295 Create", None))
        self.label_list_combobox.setItemText(2, QCoreApplication.translate("octron_widgetui", u"\u2296 Remove", None))

#if QT_CONFIG(tooltip)
        self.label_list_combobox.setToolTip(QCoreApplication.translate("octron_widgetui", u"Select, add or remove labels", None))
#endif // QT_CONFIG(tooltip)
        self.label_list_combobox.setCurrentText(QCoreApplication.translate("octron_widgetui", u"Label ... ", None))
#if QT_CONFIG(tooltip)
        self.hard_reset_layer_btn.setToolTip(QCoreApplication.translate("octron_widgetui", u"Hard reset of the SAM2 predictor. Use this if prediction really did not go well for your data.", None))
#endif // QT_CONFIG(tooltip)
        self.hard_reset_layer_btn.setText(QCoreApplication.translate("octron_widgetui", u"\u3004 Reset", None))
        self.create_annotation_layer_btn.setText(QCoreApplication.translate("octron_widgetui", u"\u2295 Create", None))
        self.annotate_param_groupbox.setTitle(QCoreApplication.translate("octron_widgetui", u"Parameters", None))
        self.kernel_label.setText(QCoreApplication.translate("octron_widgetui", u"Opening kernel radius", None))
        self.annotate_layer_predict_groupbox.setTitle(QCoreApplication.translate("octron_widgetui", u"Batch prediction", None))
#if QT_CONFIG(tooltip)
        self.batch_predict_progressbar.setToolTip(QCoreApplication.translate("octron_widgetui", u"<html><head/><body><p>Batch predict progress bar</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.batch_predict_progressbar.setFormat(QCoreApplication.translate("octron_widgetui", u"%p%", None))
        self.skip_label.setText(QCoreApplication.translate("octron_widgetui", u"Skip", None))
#if QT_CONFIG(tooltip)
        self.skip_frames_spinbox.setToolTip(QCoreApplication.translate("octron_widgetui", u"How many frames should be skipped in\n"
"batch prediction?", None))
#endif // QT_CONFIG(tooltip)
        self.skip_frames_spinbox.setSuffix("")
        self.skip_frames_spinbox.setPrefix("")
#if QT_CONFIG(tooltip)
        self.predict_next_oneframe_btn.setToolTip(QCoreApplication.translate("octron_widgetui", u"Predict next frame", None))
#endif // QT_CONFIG(tooltip)
        self.predict_next_oneframe_btn.setText("")
#if QT_CONFIG(tooltip)
        self.predict_next_batch_btn.setToolTip(QCoreApplication.translate("octron_widgetui", u"Predict batch of next frames", None))
#endif // QT_CONFIG(tooltip)
        self.predict_next_batch_btn.setText("")
        self.toolBox.setItemText(self.toolBox.indexOf(self.annotate_tab), QCoreApplication.translate("octron_widgetui", u"Generate annotation data", None))
#if QT_CONFIG(tooltip)
        self.toolBox.setItemToolTip(self.toolBox.indexOf(self.annotate_tab), QCoreApplication.translate("octron_widgetui", u"Create annotation data for training, i.e. add segmentation or keypoint data on videos.", None))
#endif // QT_CONFIG(tooltip)
        self.train_generate_groupbox.setTitle(QCoreApplication.translate("octron_widgetui", u"Generate training data", None))
#if QT_CONFIG(tooltip)
        self.train_polygons_overall_progressbar.setToolTip(QCoreApplication.translate("octron_widgetui", u"<html><head/><body><p>Batch predict progress bar</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.train_polygons_overall_progressbar.setFormat(QCoreApplication.translate("octron_widgetui", u"%p%", None))
#if QT_CONFIG(tooltip)
        self.train_polygons_frames_progressbar.setToolTip(QCoreApplication.translate("octron_widgetui", u"<html><head/><body><p>Batch predict progress bar</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.train_polygons_frames_progressbar.setFormat(QCoreApplication.translate("octron_widgetui", u"%p%", None))
        self.train_polygons_label.setText(QCoreApplication.translate("octron_widgetui", u"label", None))
#if QT_CONFIG(tooltip)
        self.train_export_overall_progressbar.setToolTip(QCoreApplication.translate("octron_widgetui", u"<html><head/><body><p>Batch predict progress bar</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.train_export_overall_progressbar.setFormat(QCoreApplication.translate("octron_widgetui", u"%p%", None))
#if QT_CONFIG(tooltip)
        self.train_export_frames_progressbar.setToolTip(QCoreApplication.translate("octron_widgetui", u"<html><head/><body><p>Batch predict progress bar</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.train_export_frames_progressbar.setFormat(QCoreApplication.translate("octron_widgetui", u"%p%", None))
        self.train_export_label.setText(QCoreApplication.translate("octron_widgetui", u"label and split", None))
#if QT_CONFIG(tooltip)
        self.train_prune_checkBox.setToolTip(QCoreApplication.translate("octron_widgetui", u"Exclude frames in which only a subset of all\n"
"labels is present.", None))
#endif // QT_CONFIG(tooltip)
        self.train_prune_checkBox.setText(QCoreApplication.translate("octron_widgetui", u"Prune", None))
#if QT_CONFIG(tooltip)
        self.train_data_watershed_checkBox.setToolTip(QCoreApplication.translate("octron_widgetui", u"Enable watershed on mask data. This helps to separate masks that \n"
"are on the same layer and carry the same label assignment,\n"
"but should be separate entities in the training data.", None))
#endif // QT_CONFIG(tooltip)
        self.train_data_watershed_checkBox.setText(QCoreApplication.translate("octron_widgetui", u"Watershed", None))
        self.train_data_overwrite_checkBox.setText(QCoreApplication.translate("octron_widgetui", u"Overwrite", None))
        self.training_data_folder_label.setText("")
        self.generate_training_data_btn.setText(QCoreApplication.translate("octron_widgetui", u"Generate", None))
        self.train_train_groupbox.setTitle(QCoreApplication.translate("octron_widgetui", u"Train", None))
        self.num_epochs_label.setText(QCoreApplication.translate("octron_widgetui", u"Epochs", None))
        self.save_period_label.setText(QCoreApplication.translate("octron_widgetui", u"Save period", None))
#if QT_CONFIG(tooltip)
        self.num_epochs_input.setToolTip(QCoreApplication.translate("octron_widgetui", u"How many epochs in total\n"
"should be trained?\n"
"Recommended are at least ~50.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.save_period_input.setToolTip(QCoreApplication.translate("octron_widgetui", u"After how many epochs should\n"
"(intermediary) output models be saved?", None))
#endif // QT_CONFIG(tooltip)
        self.train_resume_checkBox.setText(QCoreApplication.translate("octron_widgetui", u"Resume", None))
        self.train_training_overwrite_checkBox.setText(QCoreApplication.translate("octron_widgetui", u"Overwrite", None))
#if QT_CONFIG(tooltip)
        self.launch_tensorboard_checkBox.setToolTip(QCoreApplication.translate("octron_widgetui", u"Start tensorboard (open browser window)", None))
#endif // QT_CONFIG(tooltip)
        self.launch_tensorboard_checkBox.setText(QCoreApplication.translate("octron_widgetui", u"Tensorbrd", None))
        self.yolomodel_list.setItemText(0, QCoreApplication.translate("octron_widgetui", u"Choose model ...", None))

        self.yoloimagesize_list.setItemText(0, QCoreApplication.translate("octron_widgetui", u"Img. size", None))
        self.yoloimagesize_list.setItemText(1, QCoreApplication.translate("octron_widgetui", u"640", None))
        self.yoloimagesize_list.setItemText(2, QCoreApplication.translate("octron_widgetui", u"1024", None))

#if QT_CONFIG(tooltip)
        self.yoloimagesize_list.setToolTip(QCoreApplication.translate("octron_widgetui", u"Image size used for training within YOLO", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.train_epochs_progressbar.setToolTip(QCoreApplication.translate("octron_widgetui", u"<html><head/><body><p>Batch predict progress bar</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.train_epochs_progressbar.setFormat(QCoreApplication.translate("octron_widgetui", u"%p%", None))
#if QT_CONFIG(tooltip)
        self.train_finishtime_label.setToolTip(QCoreApplication.translate("octron_widgetui", u"Approximate time of training finish", None))
#endif // QT_CONFIG(tooltip)
        self.train_finishtime_label.setText(QCoreApplication.translate("octron_widgetui", u"Finish time", None))
        self.start_stop_training_btn.setText(QCoreApplication.translate("octron_widgetui", u"Start", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.train_tab), QCoreApplication.translate("octron_widgetui", u"Train model", None))
#if QT_CONFIG(tooltip)
        self.toolBox.setItemToolTip(self.toolBox.indexOf(self.train_tab), QCoreApplication.translate("octron_widgetui", u"Train a new or existing model with generated training data", None))
#endif // QT_CONFIG(tooltip)
        self.predict_video_drop_groupbox.setTitle(QCoreApplication.translate("octron_widgetui", u"Add video files", None))
#if QT_CONFIG(tooltip)
        self.predict_video_drop_widget.setToolTip(QCoreApplication.translate("octron_widgetui", u"Drag and drop .mp4 files here", None))
#endif // QT_CONFIG(tooltip)
        self.predict_video_predict_groupbox.setTitle(QCoreApplication.translate("octron_widgetui", u"Create predictions from videos", None))
#if QT_CONFIG(tooltip)
        self.predict_overall_progressbar.setToolTip(QCoreApplication.translate("octron_widgetui", u"<html><head/><body><p>Batch predict progress bar</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.predict_overall_progressbar.setFormat(QCoreApplication.translate("octron_widgetui", u"%p%", None))
#if QT_CONFIG(tooltip)
        self.predict_current_video_progressbar.setToolTip(QCoreApplication.translate("octron_widgetui", u"<html><head/><body><p>Batch predict progress bar</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.predict_current_video_progressbar.setFormat(QCoreApplication.translate("octron_widgetui", u"%p%", None))
        self.predict_current_videoname_label.setText(QCoreApplication.translate("octron_widgetui", u"video name", None))
        self.predict_finish_time_label.setText(QCoreApplication.translate("octron_widgetui", u"Current video finishes in:", None))
#if QT_CONFIG(tooltip)
        self.prediction_iou_label.setToolTip(QCoreApplication.translate("octron_widgetui", u"This threshold determines how much overlap between bounding boxes\n"
"is allowed before they are considered to be detecting the same object.\n"
"At IOU=0 all detected objects > conf. thresh\n"
"of one label will be fused into one mask.", None))
#endif // QT_CONFIG(tooltip)
        self.prediction_iou_label.setText(QCoreApplication.translate("octron_widgetui", u"IOU", None))
#if QT_CONFIG(tooltip)
        self.predict_start_btn.setToolTip(QCoreApplication.translate("octron_widgetui", u"Yeah!", None))
#endif // QT_CONFIG(tooltip)
        self.predict_start_btn.setText(QCoreApplication.translate("octron_widgetui", u"Let's go!", None))
#if QT_CONFIG(tooltip)
        self.prediction_poly_sigma_label.setToolTip(QCoreApplication.translate("octron_widgetui", u"Gaussian smoothing of polygons. Keep this low. 0=no smoothing.", None))
#endif // QT_CONFIG(tooltip)
        self.prediction_poly_sigma_label.setText(QCoreApplication.translate("octron_widgetui", u"Polygon sigma", None))
#if QT_CONFIG(tooltip)
        self.prediction_conf_thresh_label.setToolTip(QCoreApplication.translate("octron_widgetui", u"Confidence threshold for accepting prediction results as real", None))
#endif // QT_CONFIG(tooltip)
        self.prediction_conf_thresh_label.setText(QCoreApplication.translate("octron_widgetui", u"Conf. thresh.", None))
        self.yolomodel_trained_list.setItemText(0, QCoreApplication.translate("octron_widgetui", u"Choose model ...", None))

#if QT_CONFIG(tooltip)
        self.yolomodel_trained_list.setToolTip(QCoreApplication.translate("octron_widgetui", u"OCTRON user trained models that are found in the project path", None))
#endif // QT_CONFIG(tooltip)
        self.yolomodel_tracker_list.setItemText(0, QCoreApplication.translate("octron_widgetui", u"Tracker ...", None))
        self.yolomodel_tracker_list.setItemText(1, QCoreApplication.translate("octron_widgetui", u"BoTSORT", None))
        self.yolomodel_tracker_list.setItemText(2, QCoreApplication.translate("octron_widgetui", u"ByteTrack", None))

#if QT_CONFIG(tooltip)
        self.yolomodel_tracker_list.setToolTip(QCoreApplication.translate("octron_widgetui", u"OCTRON user trained models that are found in the project path", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.open_when_finish_checkBox.setToolTip(QCoreApplication.translate("octron_widgetui", u"Open the resuts in new napari window when finished", None))
#endif // QT_CONFIG(tooltip)
        self.open_when_finish_checkBox.setText(QCoreApplication.translate("octron_widgetui", u"View results", None))
#if QT_CONFIG(tooltip)
        self.single_subject_checkBox.setToolTip(QCoreApplication.translate("octron_widgetui", u"Click this if you expect only one subject to be tracked per label", None))
#endif // QT_CONFIG(tooltip)
        self.single_subject_checkBox.setText(QCoreApplication.translate("octron_widgetui", u"1 subject", None))
        self.videos_for_prediction_list.setItemText(0, QCoreApplication.translate("octron_widgetui", u"Videos", None))
        self.videos_for_prediction_list.setItemText(1, QCoreApplication.translate("octron_widgetui", u"\u2296 Remove", None))

#if QT_CONFIG(tooltip)
        self.videos_for_prediction_list.setToolTip(QCoreApplication.translate("octron_widgetui", u"Select, add or remove labels", None))
#endif // QT_CONFIG(tooltip)
        self.videos_for_prediction_list.setCurrentText(QCoreApplication.translate("octron_widgetui", u"Videos", None))
#if QT_CONFIG(tooltip)
        self.overwrite_prediction_checkBox.setToolTip(QCoreApplication.translate("octron_widgetui", u"Overwrite previous analysis results? ", None))
#endif // QT_CONFIG(tooltip)
        self.overwrite_prediction_checkBox.setText(QCoreApplication.translate("octron_widgetui", u"Overwrite", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.predict_tab), QCoreApplication.translate("octron_widgetui", u"Analyze (new) videos", None))
#if QT_CONFIG(tooltip)
        self.toolBox.setItemToolTip(self.toolBox.indexOf(self.predict_tab), QCoreApplication.translate("octron_widgetui", u"Use trained models to run predictions on new videos", None))
#endif // QT_CONFIG(tooltip)
    # retranslateUi

