OcSort:
  is_reid: false
  name: OcSort
  parameters:
    Q_s_scaling:
      current_value: 0.0
      default_value: 0.0001
      disabled: false
      docstring: Scaling factor for process noise in scale coordinates
      gui_element: double_spin_box
      range:
      - 1.0e-05
      - 0.01
    Q_xy_scaling:
      current_value: 0.01
      default_value: 0.01
      disabled: false
      docstring: Scaling factor for process noise in position coordinates
      gui_element: double_spin_box
      range:
      - 0.0001
      - 0.1
    asso_func:
      current_value: iou
      default_value: iou
      disabled: false
      docstring: Algorithm used for data association between detections and tracks
      gui_element: combo_box
      options:
      - iou
      - hmiou
      - giou
      - ciou
      - diou
      - centroid
    delta_t:
      current_value: 3
      default_value: 3
      disabled: false
      docstring: Time window size for velocity estimation in Kalman Filter
      gui_element: spin_box
      range:
      - 1
      - 20
    det_thresh:
      current_value: 0.3
      default_value: 0.3
      disabled: false
      docstring: Detection threshold for considering detections
      gui_element: double_spin_box
      range:
      - 0.0
      - 1.0
    frame_rate:
      current_value: 30
      default_value: 30
      disabled: true
      docstring: Frame rate of the video being processed. Used to scale the track
        buffer size
      gui_element: spin_box
      range:
      - 1
      - 240
    inertia:
      current_value: 0.2
      default_value: 0.2
      disabled: false
      docstring: Motion model weight for velocity direction in matching cost
      gui_element: double_spin_box
      range:
      - 0.0
      - 1.0
    iou_threshold:
      current_value: 0.3
      default_value: 0.3
      disabled: false
      docstring: IOU threshold for determining match between detection and tracks
      gui_element: double_spin_box
      range:
      - 0.1
      - 0.9
    is_obb:
      current_value: false
      default_value: false
      disabled: true
      docstring: Work with Oriented Bounding Boxes instead of standard axis-aligned
        bounding boxes
      gui_element: checkbox
    max_age:
      current_value: 300
      default_value: 300
      disabled: false
      docstring: Maximum age (in frames) of a track before it is considered lost
      gui_element: spin_box
      range:
      - 1
      - 10000
    max_obs:
      current_value: 305
      default_value: 305
      disabled: false
      docstring: Maximum number of historical observations (bounding boxes) stored
        for each track
      gui_element: spin_box
      range:
      - 5
      - 10000
    min_conf:
      current_value: 0.1
      default_value: 0.1
      disabled: false
      docstring: Threshold for detection confidence. Detections below this threshold
        are discarded
      gui_element: double_spin_box
      range:
      - 0.0
      - 1.0
    min_hits:
      current_value: 3
      default_value: 3
      disabled: false
      docstring: Minimum number of detection hits before a track is considered confirmed
      gui_element: spin_box
      range:
      - 1
      - 20
    nr_classes:
      current_value: 5
      default_value: 5
      disabled: true
      docstring: Total number of object classes that the tracker will handle (for
        per_class=True)
      gui_element: spin_box
      range:
      - 1
      - 20
    per_class:
      current_value: true
      default_value: true
      disabled: false
      docstring: Enables class-separated tracking. When true, tracks different object
        classes separately
      gui_element: checkbox
    use_byte:
      current_value: false
      default_value: false
      disabled: false
      docstring: Whether to use BYTE association in the second association step
      gui_element: checkbox
  reid_model: none
  tracker_type: ocsort
  win_height: 540
