StrongSort:
  win_height: 560
  name: StrongSort
  is_reid: true # Is this a model that uses ReID in some form or another? 
  reid_model: 'osnet_x1_0_market1501.pt'
  parameters:
    # BaseTracker parameters
    det_thresh:
      current_value: 0.3
      default_value: 0.3
      disabled: false
      docstring: Detection threshold for considering detections
      gui_element: double_spin_box
      range:
      - 0.0
      - 1.0
      
    max_age:
      current_value: 30
      default_value: 30
      disabled: false
      docstring: Maximum age (in frames) of a track before it is considered lost
      gui_element: spin_box
      range:
      - 1
      - 10000
      
    max_obs:
      current_value: 50
      default_value: 50
      disabled: false
      docstring: Maximum number of historical observations stored for each track
      gui_element: spin_box
      range:
      - 5
      - 10000
      
    min_hits:
      current_value: 3
      default_value: 3
      disabled: false
      docstring: Minimum number of detection hits before a track is considered confirmed
      gui_element: spin_box
      range:
      - 1
      - 20
      
    iou_threshold:
      current_value: 0.3
      default_value: 0.3
      disabled: false
      docstring: IOU threshold for determining match between detection and tracks
      gui_element: double_spin_box
      range:
      - 0.1
      - 0.9
      
    per_class:
      current_value: false
      default_value: false
      disabled: false
      docstring: Enables class-separated tracking. When true, tracks different object classes separately
      gui_element: checkbox
      
    nr_classes:
      current_value: 80
      default_value: 80
      disabled: true
      docstring: Total number of object classes that the tracker will handle (for per_class=True)
      gui_element: spin_box
      range:
      - 1
      - 100
      
    asso_func:
      current_value: iou
      default_value: iou
      disabled: false
      docstring: Algorithm used for data association between detections and tracks
      gui_element: combo_box
      options:
      - iou
      - hmiou
      - giou
      - ciou
      - diou
      - centroid
      
    is_obb:
      current_value: false
      default_value: false
      disabled: true
      docstring: Work with Oriented Bounding Boxes instead of standard axis-aligned bounding boxes
      gui_element: checkbox
      
    # StrongSort-specific parameters
    half:
      current_value: false
      default_value: false
      disabled: false
      docstring: Whether to use half-precision (fp16) for faster inference
      gui_element: checkbox
      
    min_conf:
      current_value: 0.4
      default_value: 0.4
      disabled: false
      docstring: Minimum confidence threshold for detections
      gui_element: double_spin_box
      range:
      - 0.0
      - 1.0
      
    max_cos_dist:
      current_value: 0.3
      default_value: 0.3
      disabled: false
      docstring: Maximum cosine distance for ReID feature matching in Nearest Neighbor Distance Metric
      gui_element: double_spin_box
      range:
      - 0.01
      - 1.0
      
    max_iou_dist:
      current_value: 0.85
      default_value: 0.85
      disabled: false
      docstring: Maximum IoU distance for data association
      gui_element: double_spin_box
      range:
      - 0.1
      - 1.0
      
    n_init:
      current_value: 3
      default_value: 3
      disabled: false
      docstring: Number of consecutive frames required to confirm a track
      gui_element: spin_box
      range:
      - 1
      - 10
      
    nn_budget:
      current_value: 100
      default_value: 100
      disabled: false
      docstring: Maximum size of the feature library for Nearest Neighbor Distance Metric
      gui_element: spin_box
      range:
      - 10
      - 1000
      
    mc_lambda:
      current_value: 0.98
      default_value: 0.98
      disabled: false
      docstring: Weight for motion consistency in the track state estimation
      gui_element: double_spin_box
      range:
      - 0.0
      - 1.0
      
    ema_alpha:
      current_value: 0.9
      default_value: 0.9
      disabled: false
      docstring: Alpha value for exponential moving average (EMA) update of appearance features
      gui_element: double_spin_box
      range:
      - 0.0
      - 1.0
